import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import { Button, Center, Container, MANTINE_COLORS, Space, Title, useMantineTheme } from '@mantine/core';


const Home: NextPage = () => {
  const theme = useMantineTheme()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Center sx={{ backgroundColor: theme.primaryColor, color: theme.white }} py='xl'>
        <Title>Next-Place</Title>
      </Center>

      <Space h="lg" />

      <Center>
        <Link href="/game">
          <Button variant='gradient' size='xl'>Play</Button>
        </Link>
      </Center>

    </div>
  )
}

export default Home
